"""Auditable positive/negative-control threshold calibration.

The Research pipeline starts with literature/team thresholds.  This module is
the deliberately small, local calibration layer that can replace those values
only when controls generated by the *same protocol* provide enough evidence.
It has no network dependency and accepts the same nested metric payload used by
``CandidateIndex`` and ``evaluate_battery``.

The scalar :func:`calibrate_threshold` API is kept backwards compatible.  The
plural :func:`calibrate_thresholds` API is what Research uses for a complete
seven-layer battery and writes an auditable summary alongside the thresholds.
"""

from __future__ import annotations

import hashlib
import json
import math
from copy import deepcopy
from pathlib import Path
from typing import Any, Iterable

from core.integrity import object_sha256
from project_config import global_value, target_value


CALIBRATION_SCHEMA_VERSION = 2
DEFAULT_MIN_NEGATIVE_CONTROLS = 10
DEFAULT_MIN_POSITIVE_CONTROLS = 3

# Schema versions accepted when loading a control dataset. v1 is legacy and
# loads without per-record provenance; v2 (current) requires provenance.
_SUPPORTED_CALIBRATION_SCHEMA_VERSIONS = {"1", "2"}

# Metrics that controls may calibrate. Everything else keeps its
# literature/team value regardless of control separation (v3 D2).
CALIBRATION_METRIC_KEYS = (
    "L2_ipsae",
    "L4_nc_term_dist",
    "L5_hotspot_coverage",
    "L6_pose_rmsd",
    "L7_scrmsd",
)

# The score direction is part of the contract.  ``scope=target`` means that
# MDM2 and MDMX (or arbitrary approved targets) get independent cutoffs.
METRIC_SPECS = {
    "L1_plddt": {"metric": "plddt", "direction": "maximize", "scope": "global"},
    "L2_ipsae": {"metric": "ipsae", "direction": "maximize", "scope": "target"},
    "L3_dg": {"metric": "dg", "direction": "minimize", "scope": "target"},
    "L3_sc": {"metric": "sc", "direction": "maximize", "scope": "target"},
    "L3_dsasa": {"metric": "dsasa", "direction": "maximize", "scope": "target"},
    # Both pre- and post-relaxation distances must pass, so calibration uses
    # the worse (larger) distance for each control.
    "L4_nc_term_dist": {
        "metric": "nc_term_dist", "direction": "minimize", "scope": "global",
    },
    "L5_hotspot_coverage": {
        "metric": "hotspot_cov", "direction": "maximize", "scope": "target",
    },
    "L6_pose_rmsd": {"metric": "pose_rmsd", "direction": "minimize", "scope": "target"},
    "L7_scrmsd": {"metric": "scrmsd", "direction": "minimize", "scope": "global"},
}


class ControlDataError(ValueError):
    """Raised when a control dataset cannot safely be used for calibration."""


def _numbers(values: Iterable[float]) -> list[float]:
    result = []
    for value in values:
        try:
            number = float(value)
        except (TypeError, ValueError):
            continue
        if math.isfinite(number):
            result.append(number)
    return result


def _passes(value: float, threshold: float, direction: str) -> bool:
    return value >= threshold if direction == "maximize" else value <= threshold


def _protocol_hash(protocol: Any | None) -> str | None:
    if not protocol:
        return None
    payload = json.dumps(protocol, sort_keys=True, ensure_ascii=True, separators=(",", ":"))
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()[:16]


def _wilson_interval(successes: int | None, total: int, z: float = 1.96) -> list[float | None]:
    """Return a small-sample-safe 95% Wilson interval."""
    if successes is None or total <= 0:
        return [None, None]
    p = successes / total
    denominator = 1.0 + z * z / total
    centre = (p + z * z / (2.0 * total)) / denominator
    radius = (
        z
        * math.sqrt((p * (1.0 - p) / total) + (z * z / (4.0 * total * total)))
        / denominator
    )
    return [max(0.0, centre - radius), min(1.0, centre + radius)]


def calibrate_threshold(
    *,
    metric: str,
    target_id: str,
    negatives: Iterable[float],
    positives: Iterable[float] = (),
    direction: str = "maximize",
    max_false_positive_rate: float = 0.05,
    tool: str | None = None,
    protocol: dict | None = None,
) -> dict:
    """Choose the highest-recall cutoff subject to an empirical FPR ceiling.

    This function intentionally remains permissive for existing callers.  The
    batch API applies minimum-control requirements before accepting a result as
    a production calibration.
    """
    if direction not in {"maximize", "minimize"}:
        raise ValueError("direction must be maximize or minimize")
    if not 0 <= max_false_positive_rate < 1:
        raise ValueError("max_false_positive_rate must be in [0, 1)")
    neg = _numbers(negatives)
    pos = _numbers(positives)
    if not neg:
        raise ValueError("at least one valid negative-control score is required")

    candidates = sorted(set(neg + pos))
    # Add a zero-FP boundary so small control sets can still express alpha=0.
    epsilon = max(1e-12, (max(candidates) - min(candidates)) * 1e-9)
    candidates.append(
        max(candidates) + epsilon if direction == "maximize" else min(candidates) - epsilon
    )

    feasible = []
    for cutoff in candidates:
        fp = sum(_passes(value, cutoff, direction) for value in neg)
        fpr = fp / len(neg)
        if fpr <= max_false_positive_rate:
            recall = (
                sum(_passes(value, cutoff, direction) for value in pos) / len(pos)
                if pos else None
            )
            feasible.append((cutoff, fpr, recall))
    if not feasible:  # Defensive; boundary above guarantees feasibility.
        raise RuntimeError("no feasible threshold found")

    if pos:
        best_recall = max(item[2] for item in feasible)
        tied = [item for item in feasible if item[2] == best_recall]
    else:
        tied = feasible
    # Least strict among equally useful thresholds.
    cutoff, observed_fpr, recall = (
        min(tied, key=lambda item: item[0])
        if direction == "maximize"
        else max(tied, key=lambda item: item[0])
    )

    evidence_grade = "positive_control" if pos else "empirical_null"
    fp_count = round(observed_fpr * len(neg))
    tp_count = round((recall or 0.0) * len(pos)) if pos else None
    return {
        "metric": metric,
        "target_id": target_id,
        "value": cutoff,
        "operator": ">=" if direction == "maximize" else "<=",
        "direction": direction,
        "policy": "max_recall_at_fpr" if pos else "negative_control_fpr",
        "source": f"same-protocol {evidence_grade} calibration",
        "evidence_grade": evidence_grade,
        "calibration_status": "calibrated",
        "n_positive": len(pos),
        "n_negative": len(neg),
        "max_false_positive_rate": max_false_positive_rate,
        "observed_false_positive_rate": observed_fpr,
        "false_positive_count": fp_count,
        "positive_recall": recall,
        "positive_true_count": tp_count,
        "false_positive_rate_ci95": _wilson_interval(fp_count, len(neg)),
        "positive_recall_ci95": _wilson_interval(tp_count, len(pos)) if pos else [None, None],
        "tool": tool,
        "protocol_hash": _protocol_hash(protocol),
    }


def _control_label(control: dict) -> str | None:
    raw = (
        control.get("label")
        or control.get("control_type")
        or control.get("class")
        or control.get("outcome")
    )
    normalized = str(raw or "").strip().casefold().replace("_", "-")
    if normalized in {"positive", "positive-control", "pos", "success", "successful", "binder"}:
        return "positive"
    if normalized in {
        "negative", "negative-control", "neg", "failure", "failed", "nonbinder", "non-binder"
    }:
        return "negative"
    return None


def _control_id(control: dict, index: int) -> str:
    return str(
        control.get("control_id")
        or control.get("candidate_id")
        or control.get("id")
        or f"control-{index + 1}"
    )


def _control_value(control: dict, metric: str, target_id: str | None = None) -> float | None:
    """Read one metric from flat or v6 nested control payloads."""
    candidate = control.get("candidate") if isinstance(control.get("candidate"), dict) else control
    if metric == "nc_term_dist":
        values = [
            global_value(candidate, "nc_distance_pre"),
            global_value(candidate, "nc_distance_post"),
        ]
        values = _numbers(values)
        if len(values) == 2:
            return max(values)
        metric_value = candidate.get(metric)
        return _numbers([metric_value])[0] if _numbers([metric_value]) else None
    value = (
        target_value(candidate, target_id, metric)
        if target_id is not None
        else global_value(candidate, metric)
    )
    numbers = _numbers([value])
    return numbers[0] if numbers else None


def _merge_calibrated_entry(existing: dict, calibrated: dict, *, targets: list[str] | None = None) -> dict:
    merged = deepcopy(existing) if isinstance(existing, dict) else {}
    merged.update(calibrated)
    if targets is not None:
        merged["applicable_targets"] = list(targets)
    # Keep the useful audit fields, but do not leak the internal ``metric`` key
    # into the public threshold contract as a second source of truth.
    merged.pop("metric", None)
    return merged


def coerce_dataset(raw: Any) -> tuple[list[dict], dict]:
    if isinstance(raw, (list, tuple)):
        return [item for item in raw if isinstance(item, dict)], {}
    if not isinstance(raw, (dict, str, bytes)):
        try:
            return [item for item in list(raw) if isinstance(item, dict)], {}
        except TypeError:
            pass
    if not isinstance(raw, dict):
        raise ControlDataError("control dataset must be a list or object")
    controls = raw.get("controls")
    if not isinstance(controls, list):
        raise ControlDataError("control dataset requires a controls list")
    metadata = raw.get("metadata") or raw.get("_meta") or {}
    if not isinstance(metadata, dict):
        metadata = {}
    return [item for item in controls if isinstance(item, dict)], metadata


def validate_control_metadata(
    metadata: dict,
    *,
    project_id: str | None = None,
    approved_digest: str | None = None,
    protocol: Any | None = None,
    protocol_hash: str | None = None,
    scoring_implementation: dict | None = None,
) -> dict:
    """Validate and normalize the binding metadata for a control payload.

    Schema policy (explicit, not caller-negotiable): the file's declared
    ``schema_version`` must be one of ``_SUPPORTED_CALIBRATION_SCHEMA_VERSIONS``.
    v1 is legacy and loads without per-record provenance; v2 (current) requires
    provenance (enforced separately by :func:`validate_control_provenance`).
    """
    metadata = dict(metadata or {})
    missing = [
        key for key in ("project_id", "approved_digest", "schema_version")
        if metadata.get(key) in (None, "")
    ]
    if not metadata.get("protocol") and not metadata.get("protocol_hash"):
        missing.append("protocol/protocol_hash")
    if str(metadata.get("schema_version")) == "2" and not isinstance(
        metadata.get("scoring_implementation"), dict
    ):
        missing.append("scoring_implementation")
    if missing:
        raise ControlDataError(
            "control dataset metadata is missing required binding fields: "
            + ", ".join(missing)
        )
    if not project_id:
        raise ControlDataError("current approved project_id is required for calibration")
    if not approved_digest:
        raise ControlDataError("current approved_digest is required for calibration")
    if metadata["project_id"] != project_id:
        raise ControlDataError("control dataset project_id does not match approved project")
    if metadata["approved_digest"] != approved_digest:
        raise ControlDataError("control dataset approved_digest does not match approved project")
    if str(metadata["schema_version"]) not in _SUPPORTED_CALIBRATION_SCHEMA_VERSIONS:
        raise ControlDataError("control dataset schema_version is not supported")
    observed_hash = metadata.get("protocol_hash") or _protocol_hash(metadata.get("protocol"))
    declared_hash = _protocol_hash(metadata.get("protocol"))
    if metadata.get("protocol_hash") and declared_hash and metadata["protocol_hash"] != declared_hash:
        raise ControlDataError("control dataset protocol and protocol_hash disagree")
    expected_hash = protocol_hash or _protocol_hash(protocol)
    if not expected_hash:
        raise ControlDataError("current scoring protocol/protocol_hash is required for calibration")
    if observed_hash != expected_hash:
        raise ControlDataError("control dataset protocol does not match current scoring protocol")
    if (
        scoring_implementation is not None
        and metadata.get("scoring_implementation") != scoring_implementation
    ):
        raise ControlDataError(
            "control dataset scoring implementation does not match current scorer"
        )
    metadata["protocol_hash"] = observed_hash
    return metadata


def validate_control_provenance(controls, *, version=None) -> None:
    """Reject v2 control records that lack per-record provenance.

    v1 datasets keep their legacy behaviour.  For v2, every record must declare
    a label (``positive``/``negative``), a role, and a source reference
    (``pdb_id`` and/or ``doi``); missing provenance makes the dataset unsafe to
    use as an audited threshold override.
    """
    if str(version or CALIBRATION_SCHEMA_VERSION) != "2":
        return
    for index, control in enumerate(controls):
        if _control_label(control) is None:
            raise ControlDataError(
                "control dataset v2 requires label positive/negative; "
                f"missing or invalid on {_control_id(control, index)}"
            )
        if not str(control.get("role") or "").strip():
            raise ControlDataError(
                "control dataset v2 requires per-record role; "
                f"missing on {_control_id(control, index)}"
            )
        source = control.get("source") if isinstance(control.get("source"), dict) else {}
        reference = source.get("pdb_id") or source.get("doi")
        if not reference:
            raise ControlDataError(
                "control dataset v2 requires per-record provenance "
                f"(source.pdb_id or source.doi); missing on {_control_id(control, index)}"
            )


def load_control_dataset(
    path: str | Path,
    *,
    project_id: str | None = None,
    approved_digest: str | None = None,
    protocol: Any | None = None,
    protocol_hash: str | None = None,
) -> tuple[list[dict], dict]:
    """Load a control dataset only when its production binding is complete.

    A labelled control file is allowed to replace Research thresholds only when
    it proves which approved project, configuration digest, scoring protocol,
    and calibration schema produced it.  Silent acceptance of an unbound file
    would make the calibration layer an un-audited threshold override.
    """
    source = Path(path)
    try:
        payload = json.loads(source.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise ControlDataError(f"cannot read control dataset: {type(exc).__name__}") from exc
    controls, metadata = coerce_dataset(payload)
    payload_meta = payload if isinstance(payload, dict) else {}
    for key in (
        "project_id", "approved_digest", "protocol", "protocol_hash",
        "scoring_implementation", "schema_version",
    ):
        if key in payload_meta and key not in metadata:
            metadata[key] = payload_meta[key]
    metadata = validate_control_metadata(
        metadata,
        project_id=project_id,
        approved_digest=approved_digest,
        protocol=protocol,
        protocol_hash=protocol_hash,
    )
    validate_control_provenance(controls, version=metadata.get("schema_version"))
    if not controls:
        raise ControlDataError("control dataset contains no control records")
    return controls, metadata


def calibrate_thresholds(
    *,
    controls: Iterable[dict] | dict,
    thresholds: dict | None = None,
    target_ids: Iterable[str] = (),
    protocol: Any | None = None,
    protocol_hash: str | None = None,
    max_false_positive_rate: float = 0.05,
    min_positive_recall: float = 0.50,
    min_negative_controls: int = DEFAULT_MIN_NEGATIVE_CONTROLS,
    min_positive_controls: int = DEFAULT_MIN_POSITIVE_CONTROLS,
    metric_keys: Iterable[str] | None = None,
) -> tuple[dict, dict]:
    """Calibrate the seven-layer battery from labelled control records.

    Insufficient controls never change a threshold.  The returned audit tells
    Research exactly which metrics were calibrated, skipped, or missing.  For
    target-scoped metrics, cutoffs are stored under the existing ``targets``
    override field so ``threshold_for_target`` remains the single resolver.

    Only metrics listed in ``metric_keys`` (default: ``CALIBRATION_METRIC_KEYS``)
    may be replaced by control calibration; other metrics are reported in
    ``audit["excluded_keys"]`` and keep their existing values.
    """
    records, dataset_meta, target_ids = _normalize_calibration_inputs(
        controls, target_ids, min_negative_controls, min_positive_controls,
        min_positive_recall,
    )
    if isinstance(metric_keys, str):
        metric_keys = (metric_keys,)
    eligible_keys = frozenset(
        str(key).strip()
        for key in (metric_keys if metric_keys is not None else CALIBRATION_METRIC_KEYS)
        if str(key).strip()
    )
    calibration_parameters = {
        "metric_keys": sorted(eligible_keys),
        "target_ids": sorted(target_ids),
        "max_false_positive_rate": max_false_positive_rate,
        "min_positive_recall": min_positive_recall,
        "min_negative_controls": min_negative_controls,
        "min_positive_controls": min_positive_controls,
    }
    dataset_identity = controls if isinstance(controls, dict) else records
    output = deepcopy(thresholds or {})
    audit = _build_calibration_audit(
        records, dataset_meta, protocol, protocol_hash,
        min_positive_controls, min_negative_controls,
        max_false_positive_rate, min_positive_recall,
        control_dataset_sha256=object_sha256(dataset_identity),
        calibration_parameters=calibration_parameters,
        scoring_implementation=dataset_meta.get("scoring_implementation"),
    )
    _, invalid, positives, negatives = _label_control_records(records, audit)
    expected_protocol_hash = audit["protocol_hash"]
    for key, spec in METRIC_SPECS.items():
        if key not in eligible_keys:
            audit["metrics"][key] = {
                "status": "not_calibration_eligible",
                "reason": "metric outside core calibration scope",
            }
            audit["excluded_keys"].append(key)
            continue
        scopes = target_ids if spec["scope"] == "target" else [None]
        if spec["scope"] == "target" and not scopes:
            audit["metrics"][key] = {
                "status": "missing_target_ids",
                "reason": "target-scoped calibration requires approved target IDs",
            }
            audit["skipped_keys"].append(key)
            continue
        for scope in scopes:
            _calibrate_metric_scope(
                key, scope, spec, positives, negatives, output, audit,
                target_ids, protocol, dataset_meta,
                min_negative_controls, min_positive_controls,
                max_false_positive_rate, min_positive_recall,
                expected_protocol_hash,
            )

    _finalize_calibration_status(audit, records, invalid)
    return output, audit


def _normalize_calibration_inputs(
    controls: Iterable[dict] | dict,
    target_ids: Iterable[str],
    min_negative_controls: int,
    min_positive_controls: int,
    min_positive_recall: float,
) -> tuple[list, dict, list[str]]:
    records, dataset_meta = coerce_dataset(controls)
    target_ids = [str(item).strip() for item in target_ids if str(item).strip()]
    if not isinstance(min_negative_controls, int) or min_negative_controls < 1:
        raise ValueError("min_negative_controls must be a positive integer")
    if not isinstance(min_positive_controls, int) or min_positive_controls < 1:
        raise ValueError("min_positive_controls must be a positive integer")
    if not 0 <= min_positive_recall <= 1:
        raise ValueError("min_positive_recall must be in [0, 1]")
    return records, dataset_meta, target_ids


def _build_calibration_audit(
    records: list,
    dataset_meta: dict,
    protocol: Any | None,
    protocol_hash: str | None,
    min_positive_controls: int,
    min_negative_controls: int,
    max_false_positive_rate: float,
    min_positive_recall: float,
    *,
    control_dataset_sha256: str,
    calibration_parameters: dict,
    scoring_implementation: dict | None,
) -> dict[str, Any]:
    protocol_identity = protocol or dataset_meta.get("protocol")
    return {
        "schema_version": CALIBRATION_SCHEMA_VERSION,
        "status": "not_configured" if not records else "pending_controls",
        "controls_total": len(records),
        "n_positive_controls": 0,
        "n_negative_controls": 0,
        "min_positive_controls": min_positive_controls,
        "min_negative_controls": min_negative_controls,
        "max_false_positive_rate": max_false_positive_rate,
        "min_positive_recall": min_positive_recall,
        "control_dataset_sha256": control_dataset_sha256,
        "protocol_identity": deepcopy(protocol_identity),
        "scoring_implementation": deepcopy(scoring_implementation),
        "calibration_parameters": calibration_parameters,
        "calibration_parameters_sha256": object_sha256(calibration_parameters),
        "protocol_hash": (
            protocol_hash
            or _protocol_hash(protocol_identity)
            or dataset_meta.get("protocol_hash")
        ),
        "metrics": {},
        "calibrated_keys": [],
        "skipped_keys": [],
        "excluded_keys": [],
    }


def _label_control_records(
    records: list, audit: dict
) -> tuple[list[tuple[int, dict, str]], list[str], list, list]:
    labelled: list[tuple[int, dict, str]] = []
    invalid = []
    expected_protocol_hash = audit["protocol_hash"]
    observed_protocol_hashes = set()
    for index, record in enumerate(records):
        record_protocol_hash = record.get("protocol_hash") or _protocol_hash(record.get("protocol"))
        if record_protocol_hash:
            observed_protocol_hashes.add(record_protocol_hash)
            if expected_protocol_hash and record_protocol_hash != expected_protocol_hash:
                invalid.append(_control_id(record, index))
                continue
        label = _control_label(record)
        if label is None:
            invalid.append(_control_id(record, index))
            continue
        labelled.append((index, record, label))
    if len(observed_protocol_hashes) > 1 and not expected_protocol_hash:
        audit["protocol_mismatch"] = sorted(observed_protocol_hashes)
        invalid.extend(_control_id(record, index) for index, record, _ in labelled)
        labelled = []
    positives = [item for item in labelled if item[2] == "positive"]
    negatives = [item for item in labelled if item[2] == "negative"]
    audit["n_positive_controls"] = len(positives)
    audit["n_negative_controls"] = len(negatives)
    if invalid:
        audit["invalid_controls"] = invalid
    return labelled, invalid, positives, negatives


def _calibrate_metric_scope(
    key: str,
    scope: str | None,
    spec: dict,
    positives: list,
    negatives: list,
    output: dict,
    audit: dict,
    target_ids: list[str],
    protocol: Any | None,
    dataset_meta: dict,
    min_negative_controls: int,
    min_positive_controls: int,
    max_false_positive_rate: float,
    min_positive_recall: float,
    expected_protocol_hash: str | None,
) -> None:
    scope_key = f"{key}:{scope}" if scope else key
    pos_values = []
    neg_values = []
    pos_ids = []
    neg_ids = []
    for index, record, label in positives:
        value = _control_value(record, spec["metric"], scope)
        if value is not None:
            pos_values.append(value)
            pos_ids.append(_control_id(record, index))
    for index, record, label in negatives:
        value = _control_value(record, spec["metric"], scope)
        if value is not None:
            neg_values.append(value)
            neg_ids.append(_control_id(record, index))
    metric_audit: dict[str, Any] = {
        "metric": key,
        "target_id": scope,
        "direction": spec["direction"],
        "n_positive": len(pos_values),
        "n_negative": len(neg_values),
        "positive_control_ids": pos_ids,
        "negative_control_ids": neg_ids,
        "protocol_hash": audit["protocol_hash"],
    }
    if len(neg_values) < min_negative_controls or len(pos_values) < min_positive_controls:
        metric_audit.update({
            "status": "insufficient_controls",
            "reason": (
                f"need >= {min_negative_controls} negatives and "
                f">= {min_positive_controls} positives"
            ),
        })
        audit["metrics"][scope_key] = metric_audit
        audit["skipped_keys"].append(scope_key)
        return
    calibrated = calibrate_threshold(
        metric=key,
        target_id=scope or "global",
        negatives=neg_values,
        positives=pos_values,
        direction=spec["direction"],
        max_false_positive_rate=max_false_positive_rate,
        tool=(protocol or dataset_meta.get("protocol") or {}).get("tool")
        if isinstance(protocol or dataset_meta.get("protocol"), dict)
        else None,
        protocol=protocol or dataset_meta.get("protocol"),
    )
    if expected_protocol_hash:
        calibrated["protocol_hash"] = expected_protocol_hash
    metric_audit.update({
        "status": "calibrated",
        "value": calibrated["value"],
        "operator": calibrated["operator"],
        "observed_false_positive_rate": calibrated["observed_false_positive_rate"],
        "positive_recall": calibrated["positive_recall"],
        "false_positive_rate_ci95": calibrated["false_positive_rate_ci95"],
        "positive_recall_ci95": calibrated["positive_recall_ci95"],
    })
    if (calibrated.get("positive_recall") or 0.0) < min_positive_recall:
        metric_audit.update({
            "status": "not_separated",
            "reason": (
                f"positive recall {calibrated.get('positive_recall')!r} "
                f"is below required {min_positive_recall}"
            ),
        })
        audit["metrics"][scope_key] = metric_audit
        audit["skipped_keys"].append(scope_key)
        return
    if scope:
        base = deepcopy(output.get(key) or {})
        overrides = base.setdefault("targets", {})
        previous = overrides.get(scope) if isinstance(overrides, dict) else {}
        overrides[scope] = _merge_calibrated_entry(
            previous if isinstance(previous, dict) else {},
            calibrated,
            targets=[scope],
        )
        base["targets"] = overrides
        base.setdefault("applicable_targets", list(target_ids))
        output[key] = base
    else:
        output[key] = _merge_calibrated_entry(
            output.get(key) or {}, calibrated, targets=target_ids or None
        )
    audit["metrics"][scope_key] = metric_audit
    audit["calibrated_keys"].append(scope_key)


def _finalize_calibration_status(audit: dict, records: list, invalid: list) -> None:
    if audit["calibrated_keys"]:
        audit["status"] = (
            "calibrated"
            if not audit["skipped_keys"]
            else "partially_calibrated"
        )
    elif records:
        metric_statuses = {
            item.get("status")
            for item in audit["metrics"].values()
            if isinstance(item, dict)
        }
        if "not_separated" in metric_statuses:
            audit["status"] = "not_separated"
        elif invalid:
            audit["status"] = "invalid_controls"
        else:
            audit["status"] = "insufficient_controls"

