"""Candidate update contract for the Execution transaction boundary.

A CandidateUpdate is emitted by a Design subprocess (replacing the direct
``CandidateIndex.add()`` call) and committed atomically by CommitManager via
``Store.commit_transaction``.

Lifecycle (transaction staging artifact, NOT a side database):

    generate  (design.py ``emit_candidate_update``)
    -> read   (iterate_design handler adapter)
    -> commit (CommitManager -> Store.commit_transaction -> CandidateIndex)
    -> discard

After commit, CandidateIndex remains the single source of truth.
CandidateUpdate never coexists with CandidateIndex as two truth sources.

Fields align with the existing candidate handoff contract produced by
``design.py _candidate_from_manifest``. The handler stages ``design_pdb`` and
``manifest`` files via ``StagingArea`` and registers them as ``StagedArtifact``
in ``ExecutionActionResult.artifacts``; ``candidate_updates`` carries the
candidate record itself for ``Store.commit_transaction``.

DEBT (Phase 1 limitation, see transaction_migration_audit.md §10):
    candidate_id is still generated by ``design.py _next_candidate_id()``, which
    reads CandidateIndex and writes ``State(candidate_count)``. This is a known
    single-process assumption (see ``_next_candidate_id`` docstring) and a
    state-write bypass outside the transaction boundary. Phase 2 / future PR
    should move candidate_id assignment into CommitManager to guarantee
    transactional ID allocation and concurrency safety. Until then the
    bypass is documented, not hidden.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass
from typing import Any, Mapping


CANDIDATE_UPDATE_SCHEMA_VERSION = 1


@dataclass(frozen=True)
class CandidateUpdate:
    """One candidate emitted by a Design subprocess for transactional commit."""

    candidate_id: str
    sequence: str
    length: int
    source_route: str
    source_batch: str
    cyclization_type: str
    cyclization_bonds: tuple[Mapping[str, str], ...]
    design_pdb_path: str
    design_pdb_hash: str
    manifest_path: str
    manifest_sha256: str
    monomer_plddt: float
    notes: str

    def __post_init__(self) -> None:
        for name in (
            "candidate_id",
            "sequence",
            "source_route",
            "source_batch",
            "cyclization_type",
            "design_pdb_path",
            "design_pdb_hash",
            "manifest_path",
            "manifest_sha256",
        ):
            value = getattr(self, name)
            if not isinstance(value, str) or not value:
                raise ValueError(f"{name} must be a non-empty string")
        if isinstance(self.length, bool) or not isinstance(self.length, int) or self.length <= 0:
            raise ValueError("length must be a positive integer")
        if isinstance(self.monomer_plddt, bool) or not isinstance(self.monomer_plddt, (int, float)):
            raise ValueError("monomer_plddt must be numeric")
        object.__setattr__(self, "cyclization_bonds", tuple(self.cyclization_bonds))

    def to_dict(self) -> dict[str, Any]:
        value = asdict(self)
        value["cyclization_bonds"] = list(self.cyclization_bonds)
        return value

    @classmethod
    def from_dict(cls, value: Mapping[str, Any]) -> "CandidateUpdate":
        if not isinstance(value, Mapping):
            raise ValueError("candidate update must be an object")
        return cls(
            candidate_id=str(value["candidate_id"]),
            sequence=str(value["sequence"]),
            length=int(value["length"]),
            source_route=str(value["source_route"]),
            source_batch=str(value["source_batch"]),
            cyclization_type=str(value["cyclization_type"]),
            cyclization_bonds=tuple(value.get("cyclization_bonds") or ()),
            design_pdb_path=str(value["design_pdb_path"]),
            design_pdb_hash=str(value["design_pdb_hash"]),
            manifest_path=str(value["manifest_path"]),
            manifest_sha256=str(value["manifest_sha256"]),
            monomer_plddt=float(value["monomer_plddt"]),
            notes=str(value.get("notes") or ""),
        )


@dataclass(frozen=True)
class CandidateUpdateBatch:
    """Envelope for the ``candidate_updates.json`` staging file emitted by design.py.

    design.py writes this to its output dir; the iterate_design handler reads
    it, converts each entry to ``CandidateUpdate``, and fills
    ``ExecutionActionResult.candidate_updates``. After CommitManager commits,
    the file is discarded -- it is never a long-lived cache or state store.
    """

    schema_version: int
    emitter: str
    source_route: str
    generated_at: str
    candidate_updates: tuple[CandidateUpdate, ...]

    def __post_init__(self) -> None:
        if self.schema_version != CANDIDATE_UPDATE_SCHEMA_VERSION:
            raise ValueError(
                f"unsupported candidate_update schema_version: {self.schema_version}"
            )
        if not isinstance(self.emitter, str) or not self.emitter:
            raise ValueError("emitter must be a non-empty string")
        object.__setattr__(self, "candidate_updates", tuple(self.candidate_updates))

    def to_dict(self) -> dict[str, Any]:
        return {
            "schema_version": self.schema_version,
            "emitter": self.emitter,
            "source_route": self.source_route,
            "generated_at": self.generated_at,
            "candidate_updates": [item.to_dict() for item in self.candidate_updates],
        }

    @classmethod
    def from_dict(cls, value: Mapping[str, Any]) -> "CandidateUpdateBatch":
        if not isinstance(value, Mapping):
            raise ValueError("candidate update batch must be an object")
        return cls(
            schema_version=int(value.get("schema_version", CANDIDATE_UPDATE_SCHEMA_VERSION)),
            emitter=str(value.get("emitter") or "design"),
            source_route=str(value.get("source_route") or ""),
            generated_at=str(value.get("generated_at") or ""),
            candidate_updates=tuple(
                CandidateUpdate.from_dict(item)
                for item in (value.get("candidate_updates") or [])
            ),
        )
